CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "login" VARCHAR(75) NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL
);

CREATE TABLE "books" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "description" VARCHAR(500) NOT NULL,
  "number_of_pages" INT NOT NULL,
  "language_id" INT NOT NULL,
  "path" VARCHAR(500) UNIQUE NOT NULL,
  "downloads" INT NOT NULL
);

CREATE TABLE "authors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "firstname" VARCHAR(100) NOT NULL,
  "lastname" VARCHAR(100) NOT NULL
);

CREATE TABLE "books_authors" (
  "book_id" INT NOT NULL,
  "author_id" INT NOT NULL
);

CREATE TABLE "tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" SERIAL UNIQUE NOT NULL
);

CREATE TABLE "books_tags" (
  "book_id" INT NOT NULL,
  "tag_id" INT NOT NULL
);

CREATE TABLE "languages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" VARCHAR(255) NOT NULL
);

CREATE TABLE "books_users" (
  "book_id" INT NOT NULL,
  "user_id" INT NOT NULL
);

ALTER TABLE "books" ADD FOREIGN KEY ("language_id") REFERENCES "languages" ("id");

ALTER TABLE "books_authors" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

ALTER TABLE "books_authors" ADD FOREIGN KEY ("author_id") REFERENCES "authors" ("id");

ALTER TABLE "books_tags" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

ALTER TABLE "books_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id");

ALTER TABLE "books_users" ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

ALTER TABLE "books_users" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
